messages:
  responses:
    successDelMessage: "✅Данные удалены"
    successAddMessage: "✅Данные сохранены"
    unknowCommandMessage: "🤷‍♂️Неизвестная команда"
    chooseIntervalMessage: "📆Выберите временной промежуток:"
    enterExpenceMessage: "🧮Введите сумму расхда в виде Категория-сумма\nНапример: Еда-500"
    enterIncomeMessage: "🧮Введите сумму дохода в виде Категория-сумма\nНапример: Зарплата-500:"
  errors:
    errorDelDataMessage: "❌Обшибка удаления данных"
    errorAddDataMessage: "❌Ошибка добавления данных"
    errorEnterData: "❌Ошибка ввода данных\nВведите сумму расхда в виде Категория-сумма\nНапример: Еда-500"
    errorNotExpence: "✏️У вас еще нет расходов.\nЧтобы добавить расход напиши /add_expence"
    errorNotIncome: "✏️У вас еще нет доходов.\nЧтобы добавить доход напиши /add_income"


